name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  get_storage: ^2.0.3
  cached_network_image:
  image_cropper: ^3.0.1
  image_picker: ^0.8.5+3
  cloud_firestore: ^4.3.1
  dropdown_textfield: ^1.0.7
  grouped_list: ^5.1.2

  firebase_storage: ^11.0.10

  permission_handler: ^10.2.0
  intl:

  get_it: ^7.2.0
  get: 4.6.5
  provider: ^6.0.2
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  crypto: ^3.0.1
  sign_in_with_apple: ^4.2.0
  ntp: ^2.0.0
  google_sign_in:
  geolocator: ^9.0.2
  google_maps_place_picker_mb: ^2.0.0-mb.21
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.2.1
  latlong2: ^0.8.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/