name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  get_storage: ^2.0.3
  cached_network_image: ^3.2.3
  image_cropper: ^3.0.1
  image_picker: ^0.8.5+3
  cloud_firestore: ^4.3.1
  dropdown_textfield: ^1.0.7
  grouped_list: ^5.1.2

  firebase_storage: ^11.0.10
#  stop_watch_timer: ^2.0.0
#  flutter_sound: ^8.4.2
  permission_handler: ^10.2.0
  intl:
#  just_audio: ^0.9.21
#  path_provider: ^2.0.11
#  flutter_svg:
  get_it: ^7.2.0
  get: 4.6.5
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/